service: GlobaLambdas

plugins:
- serverless-python-requirements

versionFunctions: false

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - venv/**
    - node_modules/**
    - .gitignore
    - package.json
    - package-lock.json
    - test_data/**
    - package/**
    - deploy/**
    - deploy.py
    - undeploy.py
    - package.sh
    - layers/**

provider:
  name: aws
  runtime: python3.6
  stage: prod
  region: ap-southeast-1
  memorySize: 128
  timeout: 120
  logRetentionInDays: 1

layers:
  common_data:
    path: layers/common_data.zip
    name: potassium40-common-data
    description: Common data files for all functions
    compatibleRuntimes:
      - python3.6
    licenseinfo: MIT
  requests_layer:
    path: layers/requests_layer.zip
    name: potassium40-requests
    description: requests package
    compatibleRunTimes:
      - python 3.6
    licenseinfo: Apache-2.0

functions:
  pottasium40_get_robots:
    handler: lambda_multiproc.get_robots
    memorySize: 1024
    timeout: 300
    description: Use Lambda functions to get robots.txt file from Cisco Umbrella 1 million
  pottasium40_compress_bucket:
    handler: compress_bucket.compress_bucket
    memorySize: 3008
    timeout: 900
    description: Compress all files in S3 bucket into 1 single zip file
