
service: potassium40

custom:
  bucketName: ${opt:bucket_name, 'p40-uuid'}

resources:
  Resources:
    p40Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}

provider:
  name: aws
  runtime: python3.7
  logRetentionDays: 1
  stage: functions
  region: ap-southeast-1
  iamRoleStatements:
  # Bucket Permissions
  - Effect: Allow
    Action:
    - s3:ListBucket
    Resource:
      Fn::Join:
        - ""
        - - "arn:aws:s3:::"
          - ${self:custom.bucketName}
  # Bucket **Objects** Permissions
  - Effect: Allow
    Action:
    - s3:PutObject
    - s3:GetObject
    - s3:DeleteObject
    - s3:PutObjectAcl
    - s3:GetObjectAcl  # ACL permissions required for file_upload
    - s3:AbortMultipartUpload
    Resource:
      Fn::Join:
        - ""
        - - "arn:aws:s3:::"
          - ${self:custom.bucketName}
          - "/*"
  environment:
    bucket_name: ${self:custom.bucketName}

package:
  exclude:
    - venv/**
    - .gitignore
    - node_modules/**
    - package.json
    - package-lock.json

functions:
  get_robots:
    handler: lambda_multiproc.get_robots
    memorySize: 1280
    timeout: 180
    description: Use Lambda functions to get robots.txt file from Cisco Umbrella 1 million
    layers:
      Fn::Join:
      - ""
      - - "arn:aws:lambda:"
        - ${opt:region, self:provider.region}
        - ":113088814899:layer:Klayers-python37-requests:"
        - "1"  # version of layer imported
  compress_bucket:
    handler: compress_bucket.compress_bucket
    memorySize: 3008
    timeout: 900
    description: Compress all files in S3 bucket into 1 single zip file
